# Generated by Django 3.2.9 on 2022-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.CharField(max_length=120, null=True)),
                ('user_name', models.CharField(blank=True, editable=False, max_length=120, null=True)),
                ('user_id', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
