# Generated by Django 3.2.9 on 2022-03-16 23:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cornix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STEP',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('step', models.CharField(max_length=20)),
                ('state', models.TextField(blank=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cornix.user')),
            ],
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coin_pair', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('amount', models.FloatField(default=0.0)),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cornix.user')),
            ],
        ),
        migrations.CreateModel(
            name='MyClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('has_funds', models.BooleanField(default=False)),
                ('start_trading', models.BooleanField(default=False)),
                ('initial_deposit_date', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(max_length=20)),
                ('myclient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cornix.user')),
            ],
        ),
    ]
