# Generated by Django 3.2.9 on 2022-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cornix', '0003_rename_step_step_next_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclient',
            name='client_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
