# Generated by Django 3.2.9 on 2022-03-18 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cornix', '0005_user_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Cornix.myclient'),
        ),
    ]
