# THIS IS THE DIALOGUE FOR CREAING A NEW CLIENT

step_1_of_3 = """
<b>New Client (Step 1 of 3):</b>
Select the exchange you'd like to trade in.
"""

step_1_2_of_3 = """
<b>New Client > Select exchange (Step 1 of 3):</b>
Cornix supports the following options in {0}

Select the exchange that you'd like to trade in
"""

step_2_of_3 = """
<b>New Client > Set name (Step 2 of 3):</b>
Now let's pick a name for your client, so you can identify it later.

We prepared a default client name for you, but you may also provide a new name of your choice.

Click on the button below to use the default client name.
Alternatively, type in your client name and send it to the bot.
"""

step_3_of_3 = """
<b>New Client > Connect Cornix to <b>{exchange} {option}</b>:</b>
• Go to your <b>{exchange} {option}</b> account
• Copy the API details
• Paste the API details in the message box below in the following format: (API Key),(API Secret)
For example: 1234, 1234

If you don't have an account at <b>{exchange} {option}</b>, click the 'Create account from scratch' option and come back to complete the set up
"""

about_cornix_auto = """
<b>Onboarding:</b>
Please, tell us what you want to know.
We take pride in our transparency.

Also, if you feel lost, you can contact our support right below.

What would you like to know?
"""

about_cornix_E = """
<b>Onboarding - </b>
<b>Tell Me About Cornix:</b>
Cornix was established over 2 years ago by traders for traders.
Thousands of customers depend on our service to automate their daily trading, and hundreds of signal providers have already joined our rapidly growing list of partners.

As our company expands we plan to continue working on our Telegram Bot and Mobile App, in order to provide our ever-growing community with the best crypto trading experience.
"""

cornix_can_do = """
<b>Onboarding - </b>
<b>What Cornix Can Do For Me:</b>
The Cornix Trading Bot allows for simple and reliable crypto trading.
Using our advanced trading and automation tools, you can either follow signals from trading groups or create your own trades with custom strategies.

Cornix provides you with:
• Saves you time and effort - instead of constantly tracking prices on exchanges and updating your orders manually, our automation tools get the job done for you.
• Reduces your risk - we offer advanced trading tools to maximize your profit and reduce your loss when things aren't going your way.
• Takes emotion out of trading - our bot helps you stay disciplined by sticking to a predefined trading strategy.
• Provides peace of mind - no matter if you work or sleep, Cornix tracks the markets 24/7 and updates your trades for you.

Also, we have a great support team who are always available for any question.
"""

made_for = """
<b>Onboarding - </b>
<b>Who Is Cornix Made For:</b>
You don't have to be an expert crypto trader to use Cornix.

No matter if you are an experienced crypto trader or a beginner, we invest time and effort into making our advanced trading tools accessible for anyone.
"""

trade_for = """
<b>Onboarding - </b>
<b>How Does Cornix Trade For Me:</b>

Cornix requires a connection to your exchange account, so we can read your portfolio information and trade on your behalf. This connection is created by entering an API key generated by the exchange into the bot.

Since your safety is important to us, make sure that you to disable withdrawal permissions when creating the API key. Your funds will never be deposited into the bot and always remain safe in your exchange account.

Once you've started trading with our bot, you'll be able to see the orders update on the exchange automatically and receive notifications in real time for every update on your ongoing trades.
"""

cornix_features = """
<b>Onboarding - </b>
<b>What Trading Features Does Cornix Offer:</b>

We make it easier than ever to use the most advanced trading features for crypto.

• Automate your trades based on Telegram channel signals, TradingView scripts and alerts.

• Connect, manage and view multiple exchanges to one account

• Create complex trades with a possible stoploss order alongside multiple entry and take-profit orders.

• Set concurrent take-profit and stoploss orders on the same balance.

• Configure automatic trailing orders, risk percents to invest, default stoploss orders, automatic entry and take-profit strategies, and more.

• Take advantage of our proprietary Optimised Configurations feature, use your signal channel configurations, or customize your trading yourself.
"""


client_creation_success_text = """
<b> Configuration > Add Client:</b>
<b>(Client Name: {0})</b>

Client added
Do you want to connect to auto-trading for this client?
"""

plan_detail = """
<b>{0}</b>

<b>Your benefits</b>:
{1}

<b>Price: <i>{2}</i></b>
<b>Billing period: <i>{3}</i></b>
"""


payment_detail = """
Please send {0} ({1}) (exact amount, after commissions) to the following address:

<code>{2}</code>

Once your payment have been confirmed, the bot will start trading
"""


subcription_warning = """
❌❌❌❌❌❌❌❌❌❌
You are currently subscribed to
<b> {0}  ⚜VIP INTEGRATED⚜</b> pack
Time remaining <b>({1}) Day(s)</b>
If you wish to proceed, bear in mind that your current subscription will be canceled.
just go back or contact @Zignaly_Admins for help.
"""

my_portfolio = """
<b>Portfolio :</b>
<b>Total :<i> {0} BTC/{1} USD</i></b>
"""

portfolio_info = """
<b>Portfolio :</b>
In the portfolio page, you will be able to see an overview of all the coins you have in the different clients you defined in the Cornix Trading Bot.
The portfolio page will be divided to different section, each representing a different client that you defined in the bot. 
At the top of the screen, you will be able to see the total balance in BTC from all your clients. 
Next to each client name, you will see the BTC amount that you have in the client.
Then, under each client you can see a row per coin that you have in the client. 
For each coin, you will see the coin name. 
To the right, you will see the available quantity of the coin that can be used in trades and the total total quantity of coins in the client (the format is {available quantity}/{total quantity}).
The next detail in each row is the BTC amount equivalent quantity of coins from that symbol. 
Finally, in parenthesis, you can see the 24 hours percent change of the coin in the exchange.
"""

bot_config = """
<b>Configuration:</b>
What would you like to configure?
"""

client_config = """
<b>Configuration > Clients:</b>
Choose a client to preform actions on below, or add a new one by clicking the '+' below
"""

configure_a_client = """
<b>Configuration > Client:</b>
'❌ Delete' button allows you to removes your client and your funds will be returned to your wallet.

Choose an option
"""

trade_history = """
<b>My Trade history:</b>
This are the following trades executed by the bot.
please note only the last 10 trades are shown.
"""